export const FORM_REGISTER = 'FORM_REGISTER';
export const FORM_CHANGE = 'FORM_CHANGE';
export const FORM_FIELD_FOCUS = 'FORM_FIELD_FOCUS';
export const FORM_FIELD_BLUR = 'FORM_FIELD_BLUR';
export const FORM_VALIDATING = 'FORM_VALIDATING';
export const FORM_VALIDATED = 'FORM_VALIDATED';
export const FORM_SUBMIT = 'FORM_SUBMIT';
export const FORM_CLEAR = 'FORM_CLEAR';
